### PR TITLE
Adding lein support for reset command.

### PR DESCRIPTION
**Pull request by gumpt**
Adding support for the reset command in migratus created in migratus' pull request [#55](https://github.com/yogthos/migratus/pull/55).

### CODE REVIEW

**Comment by yogthos** [comment]
perfect :)

**Comment by yogthos** [comment]
and just pushed to clojars

**Comment by gumpt** [comment]
Thanks again!  That was amazingly fast turnaround for two different PRs.  :+1:

**Comment by yogthos** [comment]
you did all the hard work here :)

**Pull request merged**
